global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    monitor: 'mi-monitor'

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093


scrape_configs:
  - job_name: 'PROMETHEUS_TRAEFIK'
    scrape_interval: 3s
    static_configs:
         - targets: ['localhost:9090', 'localhost:8080']

  - job_name: 'CONSUL-service-discovery'
    consul_sd_configs:
    - server: 'localhost:8500'

  - job_name: 'DNS discovery'

    dns_sd_configs:
    - names:
      - 'telemetry.eu-west.api.srv.example.org'

#grafana cloud     
remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
        username: 65549
        password: eyJrIjoiZjRhMDdlOTY0NjFhZDFmOGZlNDZkN2JiMmU0NzIwYTU1ZWFmZDdmZSIsIm4iOiJncDQiLCJpZCI6NDc1Mzk3fQ==
 

#  - job_name: 'service-discovery'
#    consul_sd_configs:
#    - server: 'localhost:8500'

#  - job_name: 'prometheus_GRUPO04'
#    scrape_interval: 2s
#    metrics_path: '/q/metrics'

